[build]
  command = "npm run build"
  directory = "backend"  
  publish = "dist"  

[functions]
  directory = "dist/functions"  # Make sure this is the directory where your serverless functions reside
